"""empty message

Revision ID: 5cb9a864133b
Revises: 8ebb24e0fdb4
Create Date: 2024-09-17 18:10:10.834398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb9a864133b'
down_revision = '8ebb24e0fdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Homeworld', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Birth_Year', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['Birth_Year'])
        batch_op.create_unique_constraint(None, ['Homeworld'])
        batch_op.create_unique_constraint(None, ['hair_color'])
        batch_op.create_unique_constraint(None, ['gender'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Birth_Year')
        batch_op.drop_column('Homeworld')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('gender')

    op.drop_table('favorites')
    op.drop_table('planets')
    # ### end Alembic commands ###
