"""empty message

Revision ID: 8c9dfda7057f
Revises: 5cb9a864133b
Create Date: 2024-09-17 19:12:40.458952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9dfda7057f'
down_revision = '5cb9a864133b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_Birth_Year_key', type_='unique')
        batch_op.drop_column('Birth_Year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Birth_Year', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('people_Birth_Year_key', ['Birth_Year'])

    # ### end Alembic commands ###
